#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sat Nov 30 15:57:01 2013

import wx
from functions import *

class Menu(wx.Frame):
	
	def __init__(self, *args, **kwds):
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		
		self.combo1 = wx.ComboBox(self, -1, choices=[u"Alunos Por Instituição", "Alunos Por Distrito", "Permilagem Alunos por Distrito", u"Percentagem Alunos por Instituiçao", u"Vagas por Colocar por Instituição", "Vagas por Colocar por Distrito"], style=wx.CB_READONLY)
		self.combo1.SetToolTip(wx.ToolTip("Select a Statistics"))
		
		self.button1 = wx.Button(self, -1, "Get Statistics")
		self.button1.Bind(wx.EVT_BUTTON, self.button1Click, self.button1)
		
		self.__set_properties()
		self.__do_layout()
        # end wxGlade
        
	def button1Click(self, event):
		Selected = self.combo1.GetSelection()
		Value = self.combo1.GetValue()
		
		if Selected == 0 :
			create_graph(get_inst('COLOC'),'Grafico - ' + Value,'Alunos','ID',False)
		elif Selected == 1 :
			create_graph(get_dist('COLOC'),'Grafico - ' + Value,'Alunos','Distritos',True)
		elif Selected == 2 :
			create_graph(get_dist_per('COLOC'),'Grafico - ' + Value,'Alunos (Permilagem)','Distritos',True)
		elif Selected == 3 :
			create_graph(get_total_perc(),'Grafico - ' + Value,'Alunos (%)','ID',False)
		elif Selected == 4 :
			create_graph(get_inst('VAGA_SOBR'),'Grafico - ' + Value,'Vagas','ID',False)
		else :
			create_graph(get_dist('VAGA_SOBR'),'Grafico - ' + Value,'Vagas','ID',True)
			
	def __set_properties(self):	
		self.SetTitle("Main Menu")
		self.combo1.SetSelection(0)

	def __do_layout(self):
		Sizer = wx.BoxSizer(wx.HORIZONTAL)
		Sizer.Add(self.combo1, 0, 0, 0)
		Sizer.Add(self.button1, 0, 0, 0)
		self.SetSizer(Sizer)
		Sizer.Fit(self)
		self.Layout()

